services:
  redis:
    image: redislabs/rejson:2.0.6
    restart: always
    ports:
      - "16379:6379"

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    labels:
      - dev.orbstack.http-port=8025
    ports:
      - "1025:1025"
      - "8025:8025"
